export const LOAD_CONF_SUCCESS = 'LOAD_CONF_SUCCESS';
export const LOAD_CONF_ERROR = 'LOAD_CONF_ERROR';
export const LOAD_NEW_QUERY_START = 'LOAD_NEW_QUERY_START';
export const LOAD_NEW_QUERY_SUCCESS = 'LOAD_NEW_QUERY_SUCCESS';
export const LOAD_NEW_QUERY_ERROR = 'LOAD_NEW_QUERY_ERROR';
export const LOAD_NEW_PAGE_START = 'LOAD_NEW_PAGE_START';
export const LOAD_NEW_PAGE_SUCCESS = 'LOAD_NEW_PAGE_SUCCESS';
export const LOAD_NEW_PAGE_ERROR = 'LOAD_NEW_PAGE_ERROR';
